//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadWords.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReadWords.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?php define( &apos;_JEXEC&apos;, 1 );
        ///// define(&apos;JPATH_BASE&apos;, &apos;/home/korablinod/korablinoddt.org.ru/docs&apos; ); // ddt
        ///// define(&apos;JPATH_BASE&apos;, &apos;/home/atkorablin/atkorablino.ru/docs&apos; ); // atkorablino
        /////###ddt-jpath###
        /////###at-jpath###
        ///define( &apos;DS&apos;, DIRECTORY_SEPARATOR );
        ////* Required Files */
        ///require_once ( JPATH_BASE .DS.&apos;includes&apos;.DS.&apos;defines.php&apos; );
        ///// /korablinoddt.org.ru/docs/includes/
        ///require_once ( JPATH_BASE .DS.&apos;includes&apos;.DS.&apos;framework.php&apos; );
        /// 
        ////* To use Joomla&apos;s Database Class */
        /////require_once (  [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string post_joomla {
            get {
                return ResourceManager.GetString("post_joomla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?php
        ///// post to WordPress site
        ///require_once( dirname(__FILE__) . &apos;/wp-load.php&apos; );
        ///require_once( dirname(__FILE__) . &apos;/wp-admin/includes/admin.php&apos; );
        ///
        ///$post_data = array(
        ///    &apos;post_title&apos;    =&gt; &apos;###title###&apos;,
        ///    &apos;post_content&apos;  =&gt; &apos;###content###&apos;,
        ///    &apos;post_status&apos;   =&gt; &apos;###status###&apos;, 
        ///    &apos;post_author&apos;   =&gt; 1, 
        ///    &apos;post_category&apos; =&gt; ###category### 
        ///);
        ///
        ///$post_id = wp_insert_post($post_data, true);
        ///print_r($post_id);
        ///
        ///$url = &apos;###url###&apos;;
        ///
        ///$description = &quot;&quot;;
        ///$file_array = array();
        ///$tm [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string post_wp {
            get {
                return ResourceManager.GetString("post_wp", resourceCulture);
            }
        }
    }
}
